name: action test
on: push

jobs:
  build:
    name: test
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: test artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: newest-installer-for-win
          path: test/index.js